spring:
  application:
    name: service-auth
  redis:
    host: 192.168.137.128
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.128:3306/spring-cloud-oauth2-db?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9098
security:
  oauth2:
    client:
      registered-redirect-uri: http://example
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/