spring:
  application:
    name: service-auth
  redis:
    host: 192.168.137.128
    database: 0
server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/