eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: service-hi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.128:3306/spring-cloud-oauth2-db?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9000/users/current
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:9000/oauth/token
      user-authorization-uri: http://localhost:9000/oauth/authorize
#      grant-type: client_credentials,password,
      scope: server


